# Generated by Django 6.0.7 on 2026-07-12 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(help_text='e.g., Heavy Commercial, Light Motor Vehicle', max_length=50)),
                ('expiry_date', models.DateField(help_text="Driver's license validity expiry date")),
                ('contact', models.CharField(max_length=20)),
                ('safety_score', models.FloatField(default=100.0, help_text='Safety performance score out of 100')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('OFF_DUTY', 'Off Duty'), ('SUSPENDED', 'Suspended')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(help_text='Unique Registration Number', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Vehicle Name/Model', max_length=100)),
                ('vehicle_type', models.CharField(help_text='e.g., Van, Truck, Prime Mover', max_length=50)),
                ('max_load', models.FloatField(help_text='Maximum load capacity in kg', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('odometer', models.IntegerField(help_text='Current odometer reading in km', validators=[django.core.validators.MinValueValidator(0)])),
                ('acquisition_cost', models.DecimalField(decimal_places=2, help_text='Purchase cost of the vehicle', max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('IN_SHOP', 'In Shop'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('cargo_weight', models.FloatField(help_text='Weight of cargo in kg', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('distance', models.FloatField(help_text='Planned distance in km', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Details of the maintenance or repair work performed')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if maintenance is currently active', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True means the vehicle is currently in shop')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('TOLL', 'Toll'), ('FINE', 'Fine/Challan'), ('PERMIT', 'State Permit'), ('OTHER', 'Other Operational Cost')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.vehicle')),
            ],
        ),
    ]
